### ISSUE TITLE
Input boolean arguments might be being ignored/git submodules

### ISSUE THREAD

**Issue by SomeoneSerge** [edolstra/flake-compat#20]
Flake inputs [since recently](https://github.com/NixOS/nix/pull/4435) support boolean arguments, including `submodules = true` for git inputs, which are supposed to trigger recursive checkout.

It seems, however, that `flake-compat` ignores those arguments:

- Flake: https://github.com/SomeoneSerge/triton.nix/blob/f1ed98b8ebad142c10032243e3a50c94dc90ffb5/flake.nix#L9
- `nix build -L` succeeds to check out microsoft/onnxruntime` recursively (paths in https://github.com/microsoft/onnxruntime/tree/master/cmake/external are available in sources)
- `./build-compat.nix` fails with

  ```
                                                                                                            
  The source directory
  /build/source/cmake/external/googletest
  does not contain a CMakeLists.txt file.
                                                                                                              
  The source directory
  ...
  The source directory
  /build/source/cmake/external/flatbuffers
  does not contain a CMakeLists.txt file.
  ```

Related:
- https://github.com/NixOS/nix/pull/4435
- https://github.com/NixOS/nix/issues/4357

**Comment by charlesbaynham** [comment]
Hi @SomeoneSerge,  I ran into this too - did you find a workaround?

**Comment by SomeoneSerge** [comment]
Hello @charlesbaynham, I actually don't remember when have I last run into this problem (or the need to use flake inputs with submodules). Lately, I've been using the new `builtins.getFlake` instead of `flake-compat`, because I more often needed "shell.nix" for impure evaluation, rather than for handling flake-less installations of Nix

I haven't tested your PR yet, but I presume it would fix the issue
