### ISSUE TITLE
bashrc is sourced

### ISSUE THREAD

**Issue by ursi** [edolstra/flake-compat#21]
```nix
{ outputs = { nixpkgs, ... }:
    let system = "x86_64-linux"; in
    { devShell.${system} =
        nixpkgs.legacyPackages.${system}.mkShell
          { shellHook = "alias"; };
    };
}
```
running this shell with `nix-shell` and flake-compat will show all the aliases defined in you bashrc, whereas running it in `nix develop` will not.

**Comment by zimbatm** [comment]
This is probably out of scope. The compact layer doesn't control how bash is being invoked.

**Comment by ursi** [comment]
Oh, so this behaviour can't be emulated inside of nix 2.3? I was hoping it could :(

**Comment by edolstra** [comment]
Right, this is more a `nix develop` issue, so you may want to reopen this issue in the `nix` repo.

**Comment by ursi** [comment]
@edolstra are you saying `nix develop` is currently working improperly, and it *should* be sourcing the bashrc?

**Comment by edolstra** [comment]
Could be, I can never remember when bashrc or bash_profile should be sourced...

**Comment by ursi** [comment]
Personally I feel like sourcing either of those in the `shellHook` is not great. I just had my own code break from it due to me changing one of my aliases.
