### ISSUE TITLE
Ability to use non-default `devShell`

### ISSUE THREAD

**Issue by sir4ur0n** [edolstra/flake-compat#31]
[Current implementation](https://github.com/edolstra/flake-compat/blob/master/default.nix#L196) hard-codes the use of `devShell.${system}` while other shells can be provided in `flake.nix` at `devShell.${system}.<whatever>`, e.g. `devShell.${system}.foo`.

It would be useful to provide means of accessing these other shells too.

**Comment by adrian-gierakowski** [comment]
this could be solved generically the solution proposed [here](https://github.com/edolstra/flake-compat/issues/51)

**Comment by adrian-gierakowski** [comment]
actually, you can actually do that with:

```nix
resultOfFlakeCompat.defaultNix.devShells.${system}.foo
```
