### ISSUE TITLE
why not add a flake.nix?

### ISSUE THREAD

**Issue by colemickens** [edolstra/flake-compat#34]
Why not add a `flake.nix` so that folks who are managing the import of `flake-compat` via flakes itself don't have to use `flake = false;`?

**Comment by Artturin** [comment]
Why complicate this?

**Comment by colemickens** [comment]
How is it a complication? It's a part of the flakes ecosystem, it's awkward to import it and have to stick `flake = false`. That feels more complicated to me, especially given the bugs around non-flake flake-imports.

**Comment by colemickens** [comment]
Also, it means I wouldn't have to come here once a month and check for updates. I would just get updates via the nix tooling (aka, the whole reason flakes is nice). It just seems obvious?

**Comment by edolstra** [comment]
> Also, it means I wouldn't have to come here once a month and check for updates.

Not sure I understand this. `nix flake update` should also work on non-flake inputs like `flake-compat`.

**Comment by colemickens** [comment]
Huh, somehow I needed someone to say it explicitly for me to get over some weird mental block. Of course I can, that's fine, since hopefully we can leave this behind someday <sup>(soonish)</sup>.

Thanks for entertaining it this long, anyway. Closing.
